# Generated by Django 4.2.2 on 2023-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('focus', 'Focus'), ('team', 'Team'), ('conference', 'Conference')], max_length=25)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
